(() => {
'use strict';
const HISTORY_KEY='arbat-training-history',CURRENT_KEY='arbat-training-current',$=id=>document.getElementById(id);
const valueOf=arrow=>arrow&&arrow.label==='M'?0:Number(arrow&&arrow.score)||0;
const arrowsOf=session=>[...(session.completed||[]).flatMap(end=>end.arrows||[]),...(session.current||[])];
const dateKey=value=>{const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return '';return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
const today=()=>{const d=new Date();d.setHours(0,0,0,0);return d;},addDays=(date,days)=>{const d=new Date(date);d.setDate(d.getDate()+days);return d;};
const parseLocalDate=key=>{const p=String(key||'').split('-').map(Number);return p.length===3?new Date(p[0],p[1]-1,p[2]):new Date(NaN);};
const readJson=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return value??fallback;}catch(_){return fallback;}};
function currentUser(){const user=window.ArbatUser&&typeof window.ArbatUser.get==='function'?window.ArbatUser.get():window.Buddy&&window.Buddy.auth&&typeof window.Buddy.auth.getUser==='function'?window.Buddy.auth.getUser():null;if(!user)return null;return{id:String(user.id??user._id??user.email??''),name:String(user.name||user.firstName||user.email||'Usuario')};}
function initials(name){return String(name||'').trim().split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toUpperCase()||'A';}
function allSessions(user){const h=readJson(HISTORY_KEY,[]),sessions=Array.isArray(h)?h.slice():[],current=readJson(CURRENT_KEY,null);if(current&&arrowsOf(current).length)sessions.push({...current,isCurrent:true});return sessions.filter(session=>{const ownerId=session.owner&&session.owner.id!=null?String(session.owner.id):'';return !ownerId||!user||!user.id||ownerId===user.id;}).map(session=>({...session,date:session.date||dateKey(session.startedAt||session.endedAt),arrows:arrowsOf(session)})).filter(session=>session.date&&session.arrows.length);}
function selectedRange(){const days=Number($('periodSelect').value)||30,end=today(),start=addDays(end,-days+1);return{days,start,end,startKey:dateKey(start),endKey:dateKey(end)};}
const filteredSessions=(range,user)=>allSessions(user).filter(session=>session.date>=range.startKey&&session.date<=range.endKey);
function dailyData(sessions,range){const map=new Map();for(let i=0;i<range.days;i++){const key=dateKey(addDays(range.start,i));map.set(key,{date:key,arrows:0,total:0,sessions:0});}sessions.forEach(session=>{const day=map.get(session.date);if(!day)return;day.sessions++;session.arrows.forEach(arrow=>{day.arrows++;day.total+=valueOf(arrow);});});return Array.from(map.values()).map(day=>({...day,average:day.arrows?day.total/day.arrows:null}));}
const formatDate=(date,options)=>new Intl.DateTimeFormat('es-BO',options).format(date);
function renderIdentity(user){const name=user?user.name:'Este dispositivo';$('athleteName').textContent=name;$('athleteAvatar').textContent=initials(name);$('dataScope').textContent=user?'Sesiones de '+name+' guardadas en este dispositivo.':'Datos guardados en este dispositivo. Inicia sesión para asociar las próximas sesiones a tu usuario.';}
function renderKpis(sessions){const arrows=sessions.flatMap(session=>session.arrows),total=arrows.reduce((sum,arrow)=>sum+valueOf(arrow),0);$('kpiSessions').textContent=String(sessions.length);$('kpiArrows').textContent=String(arrows.length);$('kpiAverage').textContent=arrows.length?(total/arrows.length).toFixed(2).replace('.',','):'—';$('kpiDays').textContent=String(new Set(sessions.map(session=>session.date)).size);}
function renderCalendar(days){const root=$('activityCalendar');root.replaceChildren();const max=Math.max(0,...days.map(day=>day.arrows)),firstDay=(parseLocalDate(days[0]?.date).getDay()+6)%7;for(let i=0;i<firstDay;i++){const blank=document.createElement('span');blank.className='activity-day is-empty';blank.setAttribute('aria-hidden','true');root.append(blank);}days.forEach(day=>{const cell=document.createElement('span'),level=!day.arrows?0:Math.max(1,Math.ceil(day.arrows/Math.max(1,max)*3));cell.className='activity-day';cell.dataset.level=String(level);cell.title=formatDate(parseLocalDate(day.date),{day:'numeric',month:'short',year:'numeric'})+': '+day.arrows+' flechas';root.append(cell);});}
function svgElement(name,attrs={}){const node=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,String(value)));return node;}
function renderChart(rootId,days,type){const root=$(rootId);root.replaceChildren();const active=type==='average'?days.filter(day=>day.average!=null):days;if(!active.some(day=>type==='average'?day.average!=null:day.arrows>0)){const empty=document.createElement('div');empty.className='chart-empty';empty.textContent='Todavía no hay datos en este período.';root.append(empty);return;}const W=680,H=220,L=42,R=12,T=14,B=30,plotW=W-L-R,plotH=H-T-B,values=active.map(day=>type==='average'?day.average:day.arrows),max=type==='average'?10:Math.max(1,...values),svg=svgElement('svg',{viewBox:'0 0 '+W+' '+H,'aria-hidden':'true',preserveAspectRatio:'none'});[0,.5,1].forEach(ratio=>{const y=T+plotH*ratio;svg.append(svgElement('line',{x1:L,y1:y,x2:W-R,y2:y,class:'grid-line'}));const label=svgElement('text',{x:L-7,y:y+4,'text-anchor':'end'});label.textContent=String(Math.round(max*(1-ratio)*10)/10).replace('.',',');svg.append(label);});if(type==='volume'){const step=plotW/days.length,barW=Math.max(1,step*.72);days.forEach((day,index)=>{const height=day.arrows/max*plotH,bar=svgElement('rect',{x:L+index*step+(step-barW)/2,y:T+plotH-height,width:barW,height:height,class:'bar',rx:Math.min(2,barW/2)}),title=svgElement('title');title.textContent=day.date+': '+day.arrows+' flechas';bar.append(title);svg.append(bar);});}else{const points=active.map(day=>{const i=days.findIndex(item=>item.date===day.date),x=L+(days.length===1?plotW/2:i/(days.length-1)*plotW),y=T+plotH-(day.average/max*plotH);return{x,y,day};});svg.append(svgElement('path',{d:points.map((point,index)=>(index?'L':'M')+point.x.toFixed(1)+' '+point.y.toFixed(1)).join(' '),class:'trend'}));points.forEach(point=>{const dot=svgElement('circle',{cx:point.x,cy:point.y,r:3.5,class:'dot'}),title=svgElement('title');title.textContent=point.day.date+': '+point.day.average.toFixed(2)+' puntos';dot.append(title);svg.append(dot);});}const every=Math.max(1,Math.ceil(days.length/5));days.forEach((day,index)=>{if(index%every&&index!==days.length-1)return;const x=L+(days.length===1?plotW/2:index/(days.length-1)*plotW),label=svgElement('text',{x,y:H-8,'text-anchor':index===0?'start':index===days.length-1?'end':'middle'});label.textContent=formatDate(parseLocalDate(day.date),{day:'numeric',month:'short'});svg.append(label);});root.append(svg);}
function renderSessions(sessions){const root=$('sessionList');root.replaceChildren();if(!sessions.length){const empty=document.createElement('p');empty.className='empty-state';empty.textContent='No hay sesiones registradas en este período.';root.append(empty);return;}sessions.slice().sort((a,b)=>String(b.startedAt||b.date).localeCompare(String(a.startedAt||a.date))).slice(0,12).forEach(session=>{const total=session.arrows.reduce((sum,arrow)=>sum+valueOf(arrow),0),average=session.arrows.length?total/session.arrows.length:0,row=document.createElement('article');row.className='session-row';const text=document.createElement('div'),title=document.createElement('h3');title.textContent=formatDate(parseLocalDate(session.date),{weekday:'short',day:'numeric',month:'long'});const meta=document.createElement('p'),ends=(session.completed||[]).length+(session.current&&session.current.length?1:0);meta.textContent=session.arrows.length+' flechas · '+ends+' andanada'+(ends===1?'':'s')+(session.isCurrent?' · En curso':'');text.append(title,meta);const score=document.createElement('div');score.className='session-score';const strong=document.createElement('strong');strong.textContent=average.toFixed(2).replace('.',',');const small=document.createElement('small');small.textContent='promedio';score.append(strong,small);row.append(text,score);root.append(row);});}
function render(){const user=currentUser(),range=selectedRange(),sessions=filteredSessions(range,user),days=dailyData(sessions,range);renderIdentity(user);$('periodDates').textContent=formatDate(range.start,{day:'numeric',month:'short',year:'numeric'})+' — '+formatDate(range.end,{day:'numeric',month:'short',year:'numeric'});renderKpis(sessions);renderCalendar(days);renderChart('volumeChart',days,'volume');renderChart('averageChart',days,'average');renderSessions(sessions);}
$('periodSelect').addEventListener('change',render);['buddy:auth-state-changed','buddy:auth-ready','buddy:user-loaded','buddy:user-updated'].forEach(eventName=>window.addEventListener(eventName,render));render();window.ArbatTrainingHistory={render,allSessions:()=>allSessions(currentUser())};
})();
